name: Assertions and static report

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: npm add @unlighthouse/cli puppeteer

      - name: Unlighthouse assertions and client
        run: unlighthouse-ci --site pricesdoors.com --build-static

      - name: Deploy report to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: '.unlighthouse'
          production-branch: main
          production-deploy: true
          github-token: ${{ secrets.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 }}
          deploy-message: "New Release Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.5En0cT4RPrspRUaNlrTr45avKVGWbVD3rawyvS0Cafk }}
          NETLIFY_SITE_ID: ${{ secrets.793b7564-4750-40d3-bf62-c86f7673e098 }}
        timeout-minutes: 1
